name: Mini Project JMeter Rest API

on: 
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
    action_build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: ibiqlik/action-yamllint@master
        with:
          testfilePath:  minipro_cicd/testAPI/API_MiniPro.jmx
          outputReportsFolder: reports/
